// Defines the structure for an animation's settings, generated by the AI
export interface AnimationSettings {
    // Particle
    particleShape: 'circle' | 'square' | 'triangle' | 'star' | 'line' | 'hexagon';
    particleSize: number; // 5-50
    particleCount: number; // 10-500

    // Color
    colorPalette: string[]; // 2-5 hex colors
    colorStrategy: 'solid' | 'random-from-palette' | 'palette-sequence' | 'random-lerp';
    
    // Background
    backgroundStyle: 'solid' | 'radial-gradient' | 'linear-gradient' | 'subtle-noise';
    backgroundColor: string; // The primary background color, or first color for gradients

    // Motion
    motionPath: 'linear' | 'sine' | 'circular' | 'vortex' | 'gravity' | 'anti-gravity';
    motionDuration: number; // 2000-20000ms
    motionEasing: 'linear' | 'easeInSine' | 'easeOutSine' | 'easeInOutSine' | 'easeInQuad' | 'easeOutQuad' | 'easeInOutQuad' | 'easeOutCubic' | 'easeInOutCubic';

    // Interaction & Physics
    particleDistribution: 'uniform' | 'center-burst' | 'top-edge' | 'bottom-edge' | 'follow-mouse';
    edgeCollision: 'bounce' | 'wrap' | 'destroy' | 'absorb';

    // Lifecycle & Appearance
    rotationStyle: 'none' | 'constant-cw' | 'constant-ccw' | 'random-direction' | 'spin-on-bounce';
    scaleBehaviour: 'constant' | 'pulse' | 'shrink-over-life' | 'grow-over-life' | 'random-flicker';
    opacityBehaviour: 'constant' | 'fadeIn' | 'fadeOut' | 'pulse';
}

// Defines the structure for a saved animation, including its prompt and settings
export interface GeneratedAnimation {
    id: string;
    prompt: string;
    settings: AnimationSettings;
}
