// Defines the structure for an animation's settings, generated by the AI
export interface AnimationSettings {
    shape: 'circle' | 'square' | 'triangle' | 'star';
    count: number;
    colorPalette: string[];
    motion: 'swirl' | 'explode' | 'fall' | 'grid-stagger' | 'float';
    duration: number;
    easing: 'linear' | 'easeInSine' | 'easeOutSine' | 'easeInOutSine' | 'easeInQuad' | 'easeOutQuad' | 'easeInOutQuad';
    size: number;
    backgroundColor: string;
}

// Defines the structure for a saved animation, including its prompt and settings
export interface GeneratedAnimation {
    id: string;
    prompt: string;
    settings: AnimationSettings;
}
